server:
  port: 8080

spring:
  cloud:
    gateway:
      routes:
        - id: auth-service
          uri: lb://auth-service
          predicates:
            - Path=/api/v1/auth/**
          filters:
            - name: CircuitBreaker
              args:
                name: authService
                fallbackUri: forward:/auth-fallback
        - id: patient-service
          uri: lb://patient-service
          predicates:
            - Path=/api/v1/patients/**
          filters:
            - name: CircuitBreaker
              args:
                name: patientService
                fallbackUri: forward:/patient-fallback
        - id: doctor-service
          uri: lb://doctor-service
          predicates:
            - Path=/api/v1/doctors/**
          filters:
            - name: CircuitBreaker
              args:
                name: doctorService
                fallbackUri: forward:/doctor-fallback
        - id: appointment-service
          uri: lb://appointment-service
          predicates:
            - Path=/api/v1/appointments/**
          filters:
            - name: CircuitBreaker
              args:
                name: appointmentService
                fallbackUri: forward:/appointment-fallback
        - id: billing-service
          uri: lb://billing-service
          predicates:
            - Path=/api/v1/billing/**
          filters:
            - name: CircuitBreaker
              args:
                name: billingService
                fallbackUri: forward:/billing-fallback
        - id: report-service
          uri: lb://report-service
          predicates:
            - Path=/api/v1/reports/**
          filters:
            - name: CircuitBreaker
              args:
                name: reportService
                fallbackUri: forward:/report-fallback

resilience4j:
  circuitbreaker:
    configs:
      default:
        registerHealthIndicator: true
        slidingWindowSize: 10
        minimumNumberOfCalls: 5
        permittedNumberOfCallsInHalfOpenState: 3
        waitDurationInOpenState: 5s
        failureRateThreshold: 50
    instances:
      authService:
        baseConfig: default
      patientService:
        baseConfig: default
      doctorService:
        baseConfig: default
      appointmentService:
        baseConfig: default
      billingService:
        baseConfig: default
      reportService:
        baseConfig: default
