eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true

spring:
  kafka:
    bootstrap-servers: localhost:9092

resilience4j:
  circuitbreaker:
    configs:
      default:
        registerHealthIndicator: true
        slidingWindowSize: 10
        permittedNumberOfCallsInHalfOpenState: 3
        slidingWindowType: COUNT_BASED
        minimumNumberOfCalls: 5
        waitDurationInOpenState: 5s
        failureRateThreshold: 50
        eventConsumerBufferSize: 10
    instances:
      appointmentService:
        baseConfig: default
      patientService:
        baseConfig: default
      authService:
        baseConfig: default
      doctorService:
        baseConfig: default
      billingService:
        baseConfig: default
      reportService:
        baseConfig: default
  retry:
    configs:
      default:
        maxAttempts: 3
        waitDuration: 2s
        enableExponentialBackoff: true
        exponentialBackoffMultiplier: 2
    instances:
      appointmentService:
        baseConfig: default
      patientService:
        baseConfig: default
      authService:
        baseConfig: default
      doctorService:
        baseConfig: default
      billingService:
        baseConfig: default
      reportService:
        baseConfig: default
